spring:
  datasource:
    url: jdbc:mysql://localhost/polarbear
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create